<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [1]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [2]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [3]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

### 1.2 Accessing data from a list (or array)

In [8]:
print(py_real_names[0]) # Use of zero-based index

Natasha Romanoff


In [5]:
print(py_super_names[0])

Black Widow


In [6]:
print(py_super_names[2])    # Forward indexing 
                            # We need to know the size 
                            # beforehand for this to work.

Doctor Strange


In [7]:
print(py_super_names[-1])   # Reverse indexing

Doctor Strange


### 1.3 Accessing data from a dictionary

In [13]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  } # Each key to its own indiv value

print(superhero_info["Natasha Romanoff"])

Black Widow


In [11]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [12]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [14]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]
#2 lists in one

## 2 Lists vs. Arrays

### 2.1 Size

In [15]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [16]:
len(py_list_2d) # Number of elements inside list

10

In [17]:
len(np_array_2d)

10

In [18]:
np_array_2d.shape

(10, 2)

### 2.2 Arrays are fussy about type

In [21]:
py_list = [1, 1.5, 'A'] # numbers are converted to English (' ')
np.array(py_list)       # NumPy arrays tolerate only a single type.

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [22]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [23]:
py_list + 10        # Won't work!

TypeError: can only concatenate list (not "int") to list

In [24]:
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [25]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [26]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [27]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [28]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [31]:
py_list*2   # multiplying number to list = list length grows

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [32]:
np_array*2 # array multiplies its elements by the number

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [33]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [34]:
py_list**2                      # Won't work!

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [35]:
np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [36]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [37]:
py_list == 3     # Works, but what IS the question?

False

In [40]:
py_list == [1, 2, 3, 4, 5]

True

In [44]:
py_list[4] > 3      # Won't work!

True

In [41]:
np_array == 3

array([False, False,  True, False, False])

In [42]:
np_array > 3  

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [45]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [46]:
sum(py_list)     # sum() is a base Python function

15

In [47]:
max(py_list)     # max() is a base Python function

5

In [48]:
min(py_list)     # min() is a base Python function

1

In [49]:
py_list.sum()   # Won't work!

AttributeError: 'list' object has no attribute 'sum'

In [50]:
np_array.sum()

15

In [52]:
np_array.mean()

3.0

In [51]:
np_array.max()

5

In [53]:
np_array.min()

1

## Exercise 1 :  Total recall?

Similarities:
1. Both can store data.
*2. Data must be accessed using a zero-based index (i.e. 1st value is actually the 0th value.*

Differences:
1. Operations to lists target the whole list, while operations to arrays target each individual element in the array.
*2. Arrays only tolerate a single type of data (e.g. either English only or numbers only).*

Dictionary: A list which on each line, each key is assigned to one value *(key-value structure)*.

## Exercise 2 :  Index me

In [65]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])   # Prints 'a1'
print(py_list[2])   # Prints 'c3'
print(py_list[4])   # Prints 'e5'
print(py_list[6])   # Prints 'g7'
print(py_list[8])   # Prints 'i9'

a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [69]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()
print(superhero_info['Tony Stark'],
      superhero_info['Natasha Romanoff'],
      superhero_info['Stephen Strange'])

IRON MAN BLACK WIDOW DOCTOR STRANGE


## Exercise 4 :  How many ones

In [74]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]
np_numbers = np.array(numbers)
sum(np_numbers == 1)

9