<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [2]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

- **Subsetting** means to ‘select’.
- **Indexing**: selecting one element.
- **Slicing**: selecting a range of elements.

### 1.2 Subsetting by masking (Arrays only)

In [3]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)

[False False False  True  True  True  True  True  True  True]


In [6]:
np_array[my_mask] # show me only those that are True
                  # subsetting by masking only works with NumPy arrays.

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
np_array[~(np_array > 3)]                         # '~' means 'NOT'

array([1, 2, 3])

In [9]:
np_array[(np_array > 3) & (np_array < 8)]         # '&' means 'AND'

array([4, 5, 6, 7])

In [10]:
np_array[(np_array < 3) | (np_array > 8)]         # '|' means 'OR'

array([ 1,  2,  9, 10])

In [11]:
np_array[(np_array < 3) & (np_array > 8)]         # '&' means 'AND'

array([], dtype=int32)

### 1.3 Indexing & Slicing 2D Lists

In [ ]:

# Your code here


### 1.4 Indexing & Slicing 2D Arrays

In [ ]:

# Your code here


### 1.5 Growing lists

In [ ]:

# Your code here


## 2 Some loose ends

### 2.1 Tuples

In [ ]:

# Your code here


### 2.2 Be VERY careful when copying

In [ ]:

# Your code here


## Exercise 1 :  Total recall?

In [ ]:



# Your solution here




## Exercise 2 :  Show me the ‘odd’ letters

In [ ]:



# Your solution here


