<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [2]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

- **Subsetting** means to ‘select’.
- **Indexing**: selecting one element.
- **Slicing**: selecting a range of elements.

### 1.2 Subsetting by masking (Arrays only)

In [3]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)

[False False False  True  True  True  True  True  True  True]


In [6]:
np_array[my_mask] # show me only those that are True
                  # subsetting by masking only works with NumPy arrays.

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
np_array[~(np_array > 3)]                         # '~' means 'NOT'

array([1, 2, 3])

In [9]:
np_array[(np_array > 3) & (np_array < 8)]         # '&' means 'AND'

array([4, 5, 6, 7])

In [10]:
np_array[(np_array < 3) | (np_array > 8)]         # '|' means 'OR'

array([ 1,  2,  9, 10])

In [11]:
np_array[(np_array < 3) & (np_array > 8)]         # '&' means 'AND'

array([], dtype=int32)

### 1.3 Indexing & Slicing 2D Lists

In [1]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

In [2]:
py_list_2d[3]        # What is at position 4 (index 3)?

[4, 'D']

In [3]:
py_list_2d[3][0]     # FIRST element at position 4 (index 3)

4

In [4]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [5]:
py_list_2d[:3][0]

[1, 'A']

In [6]:
py_list_2d[3:6][0]

[4, 'D']

### 1.4 Indexing & Slicing 2D Arrays

In [7]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

In [8]:
np_array_2d[3]       # What is at position 4 (index 3)?

array(['4', 'D'], dtype='<U11')

In [9]:
np_array_2d[3, 0]    # FIRST element at position 4 (index 3)

'4'

Syntax for arrays uses just a **single** pair of square brackets ([ ]).

In [10]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [11]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U11')

In [12]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U11')

In [13]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

### 1.5 Growing lists

In [14]:
x=[1]*10
x               # I am lazy to type print()
                # Let Jupyter do the hard work.

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [15]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [16]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [17]:
x=[1]
x+= [2, 3, 4]
x

[1, 2, 3, 4]

In [18]:
x=[1]
x= [2, 3, 4] + x
x

[2, 3, 4, 1]

In [19]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

In [20]:
a=(1, 2, 3)     # Define tuple

Tuple: List which uses (), but cannot change the data inside

In [21]:
print(a[0])    # Access data

1


In [22]:
# The following will NOT work
a[0]=-1
a[0] += [10]

TypeError: 'tuple' object does not support item assignment

### 2.2 Be VERY careful when copying

In [23]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [24]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

In [25]:
y

[1, 2, 3]

In [26]:
z

[1, 2, 3]

## Exercise 1 :  Total recall?

|Term|Brief description|
|:---|:--:|
|Subsetting|To select elements|
|Indexing|To select one element specifically|
|Slicing|To select a range of elements|
|Masking|To show only those that have a 'True' output from slicing|



## Exercise 2 :  Show me the ‘odd’ letters

In [27]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [28]:
np_array_2d[:, 0]

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U11')

In [33]:
np_array_2d[:, 0].astype(int)

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [34]:
np_array_2d_int = np_array_2d[:, 0].astype(int)

In [37]:
np_array_2d_int%2

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int32)

In [51]:
my_mask = np_array_2d_int%2 != 0
my_mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [53]:
np_array_2d[my_mask, 1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')